### ISSUE TITLE
BERT_pairwise_text_classification 실행 오류

### ISSUE THREAD

**Issue by MiaYangheeKim** [aisolab/nlp_classification#16]
안녕하세요.
배포해주신 BERT_pairwise_text_classification 폴더를 모두 clone하여 코드 수정없이 그대로 실행해보았는데 아래와 같은 오류가 뜹니다. 

(KoBERT_pair_py36) yanghee@blp-deep-server-1:~/PycharmProjects/BERT_pairwise_text_classification$ python3 train.py --type skt
/home/yanghee/anaconda3/envs/KoBERT_pair_py36/lib/python3.6/site-packages/mxnet/optimizer/optimizer.py:167: UserWarning: WARNING: New optimizer gluonnlp.optimizer.lamb.LAMB is overriding existing optimizer mxnet.optimizer.optimizer.LAMB
  Optimizer.opt_registry[name].__name__))
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    model = PairwiseClassifier(config, num_classes=model_config.num_classes, vocab=preprocessor.vocab)
  File "/home/yanghee/PycharmProjects/BERT_pairwise_text_classification/model/net.py", line 9, in __init__
    self.bert = BertModel(config)
  File "/home/yanghee/anaconda3/envs/KoBERT_pair_py36/lib/python3.6/site-packages/transformers/modeling_bert.py", line 631, in __init__
    self.embeddings = BertEmbeddings(config)
  File "/home/yanghee/anaconda3/envs/KoBERT_pair_py36/lib/python3.6/site-packages/transformers/modeling_bert.py", line 165, in __init__
    self.word_embeddings = nn.Embedding(config.vocab_size, config.hidden_size, padding_idx=0)
  File "/home/yanghee/anaconda3/envs/KoBERT_pair_py36/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 97, in __init__
    self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
TypeError: new() received an invalid combination of arguments - got (str, int), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (str, int)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (str, int)

가상환경에 설치된 라이브러리명과 버전은 다음과 같습니다.
Package                Version            
---------------------- -------------------
absl-py                0.9.0              
boto3                  1.13.7             
botocore               1.16.7             
cachetools             4.1.0              
certifi                2020.4.5.1         
chardet                3.0.4              
click                  7.1.2              
dataclasses            0.7                
docutils               0.15.2             
filelock               3.0.12             
gluonnlp               0.8.3              
google-auth            1.14.2             
google-auth-oauthlib   0.4.1              
graphviz               0.8.4              
grpcio                 1.28.1             
idna                   2.9                
importlib-metadata     1.6.0              
jmespath               0.9.5              
joblib                 0.14.1             
Markdown               3.2.2              
mxnet                  1.6.0              
numpy                  1.18.1             
oauthlib               3.1.0              
pandas                 1.0.1              
pip                    20.0.2             
protobuf               3.11.3             
pyasn1                 0.4.8              
pyasn1-modules         0.2.8              
python-dateutil        2.8.1              
pytz                   2020.1             
regex                  2020.5.7           
requests               2.23.0             
requests-oauthlib      1.3.0              
rsa                    4.0                
s3transfer             0.3.3              
sacremoses             0.0.43             
sentencepiece          0.1.86             
setuptools             46.1.3.post20200330
six                    1.14.0             
tensorboard            2.2.1              
tensorboard-plugin-wit 1.6.0.post3        
tokenizers             0.0.11             
torch                  1.4.0              
tqdm                   4.46.0             
transformers           2.4.1              
urllib3                1.25.9             
Werkzeug               1.0.1              
wheel                  0.34.2             
zipp                   3.1.0   

이 중 transformer를 가장 최신버전 (2.9.0)으로 설치하였을 때도 마찬가지 오류가 떳으며, 현재 2.4.1로 변경하였지만 오류는 동일합니다. 
혹시 해당 오류 해결방법 아신다면 답변주시면 감사하겠습니다.

**Comment by aisolab** [comment]
먼저 repo에 관심을 가져주셔서 감사합니다. 아마 제가 관리를 도중에 멈추어 dependency의 문제가 있을 듯 합니다. 금 주내로 update 후, test하여 알려드리겠습니다. @MiaYangheeKim

**Comment by aisolab** [comment]
@MiaYangheeKim 어느 부분인지 알아서 수정했고, 아마 정상적으로 동작할 것입니다. 전체 프로젝트 리팩토링이 곧 있을예정이니 돌려보시길 바랍니다.

**Comment by MiaYangheeKim** [comment]
@aisolab 답변이 늦었네요. 정상 작동 확인했습니다! 수정 감사합니다.
